import {flushSync} from 'react-dom';
import {registerAtlasTools} from './agent-tools';
import {useEffect,useMemo,useRef,useState} from 'react';
import {Activity,ArrowUpRight,ChevronRight,Focus,Info,Layers3,Pause,RotateCcw,RotateCw,Search,X} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Badge} from '@/components/ui/badge';
import {Slider} from '@/components/ui/slider';
import {Switch} from '@/components/ui/switch';
import {Sheet,SheetContent,SheetTitle,SheetDescription} from '@/components/ui/sheet';
import {Combobox,ComboboxInput,ComboboxContent,ComboboxList,ComboboxItem,ComboboxEmpty} from '@/components/ui/combobox';
import AnatomyScene from './scene';
import {t,tf,useLang,setLang,getLang,label,zhTerm} from './i18n';
import {DEFAULT_VISIBLE,SYSTEMS,explanation,hasNamedExplanation,systemLabel,type Atlas,type Concept,type SceneState,type SystemId,type View} from './anatomy';
const initial:SceneState={explode:0,visible:DEFAULT_VISIBLE,selected:[],isolate:false,view:'three-quarter',rotate:false,reset:0};
const VIEW_TITLES:Record<View,string>={'three-quarter':'three-quarter view',front:'front view',side:'side view',back:'back view'};
export default function Home(){
 const lang=useLang();
 const detailTitle=useRef<HTMLHeadingElement>(null);
 const [atlas,setAtlas]=useState<Atlas|null>(null),[state,setState]=useState(initial),[progress,setProgress]=useState(0),[error,setError]=useState(''),[panel,setPanel]=useState<'layers'|'search'|null>(null),[details,setDetails]=useState(false),[about,setAbout]=useState(false),[query,setQuery]=useState(''),[chosen,setChosen]=useState<Concept|null>(null);
 useEffect(()=>{const abort=new AbortController();setProgress(0);setError('');setAtlas(null);setChosen(null);setDetails(false);setState({...initial,visible:DEFAULT_VISIBLE});fetch('/models/atlas.json',{signal:abort.signal}).then(r=>{if(!r.ok)throw new Error(t('The anatomy catalogue could not be loaded.',getLang()));return r.json();}).then(data=>setAtlas(data as Atlas)).catch(e=>{if(e.name!=='AbortError')setError(e.message);});return()=>abort.abort();},[]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();setPanel('search');setDetails(false);}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[]);
 const parts=useMemo(()=>new Map(atlas?.parts.map(p=>[p.id,p])),[atlas]);
 const counts=useMemo(()=>Object.fromEntries(SYSTEMS.map(s=>[s.id,atlas?.parts.filter(p=>p.system===s.id).length??0])),[atlas]);
 const activeSystems=SYSTEMS.filter(s=>counts[s.id]>0);
 const selectedParts=state.selected.map(id=>parts.get(id)).filter(p=>!!p),selected=selectedParts[0],system=SYSTEMS.find(s=>s.id===selected?.system);
 const visibleCount=atlas?.parts.filter(p=>state.isolate?state.selected.includes(p.id):state.visible.includes(p.system)||state.selected.includes(p.id)).length??0;
 const results=useMemo(()=>{if(!atlas)return[];const term=query.toLowerCase().trim();if(!term)return ['heart','brain','liver','stomach','spleen','pancreas','urinary bladder','trachea'].map(name=>atlas.concepts.find(c=>c.name.toLowerCase()===name)).filter((x):x is Concept=>!!x);return atlas.concepts.filter(c=>c.name.toLowerCase().includes(term)||c.id.toLowerCase().includes(term)||(lang==='zh'&&(zhTerm(c.name,c.id)?.includes(term)??false))).sort((a,b)=>a.name.length-b.name.length).slice(0,80);},[atlas,query,lang]);
 const choose=(c:Concept)=>{setChosen(c);setState(s=>({...s,selected:c.elements,isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 useEffect(()=>{if(!atlas)return;return registerAtlasTools(atlas,c=>flushSync(()=>choose(c)));},[atlas]);
 const choosePart=(id:string)=>{const p=parts.get(id);if(!p)return;setChosen({id:p.conceptId,name:p.name,elements:[id]});setState(s=>({...s,selected:[id],isolate:false,rotate:false}));setDetails(true);setPanel(null);};
 const toggle=(id:SystemId)=>{setDetails(false);setState(s=>({...s,selected:[],isolate:false,visible:s.visible.includes(id)?s.visible.filter(x=>x!==id):[...s.visible,id]}));};
 const reset=()=>{setState(s=>({...initial,visible:DEFAULT_VISIBLE,reset:s.reset+1}));setChosen(null);setDetails(false);setPanel(null);};
 const openPanel=(next:'layers'|'search')=>{setDetails(false);setPanel(p=>p===next?null:next);};
 return <main className="studio">
  {atlas&&<AnatomyScene atlas={atlas} state={{...state,inspectorOpen:details&&selectedParts.length>0}} onSelect={choosePart} onProgress={n=>{setProgress(n);if(n===100)setError('');}} onError={setError}/>}
  <div className="vignette"/>
  <header className="identity"><div className="eyebrow"><span className="status-dot"/> {t('INTERACTIVE ANATOMY',lang)}</div><h1>{t('Human Atlas',lang)}<Badge variant="outline" className="edition">3D</Badge></h1><div className="identity-meta">{tf('{n} modeled pieces',{n:atlas?atlas.parts.length.toLocaleString():'2,234'},lang)} <span>·</span> BodyParts3D</div></header>
  <nav className="top-actions" aria-label={t('Explorer panels',lang)}>
   <Button variant="ghost" className={panel==='search'?'active':''} onClick={()=>openPanel('search')} aria-label={t('Search anatomy',lang)}><Search size={18}/><span>{t('Find a structure',lang)}</span><kbd>/</kbd></Button>
   <Button variant="ghost" className="icon-button lang-button" aria-label={lang==='zh'?'切换到英文':'Switch to Chinese'} title={lang==='zh'?'切换到英文':'切换到中文'} onClick={()=>setLang(lang==='zh'?'en':'zh')}><span className="lang-label">{lang==='zh'?'EN':'中'}</span></Button>
   <Button variant="ghost" className="icon-button" aria-label={t('About this atlas',lang)} onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}><Info size={18}/></Button>
  </nav>
  <section className={`layers-panel glass ${panel==='layers'?'mobile-open':''}`} aria-label={t('Anatomical layers',lang)}>
   <div className="panel-heading"><span>{t('Systems',lang)}</span><Button variant="ghost" className="mobile-only icon-button" onClick={()=>setPanel(null)} aria-label={t('Close systems',lang)}><X size={18}/></Button><Badge variant="secondary" className="desktop-only small-number">{activeSystems.length}</Badge></div>
   <div className="layer-presets"><Button variant="ghost" aria-pressed={activeSystems.every(x=>state.visible.includes(x.id))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:activeSystems.map(x=>x.id)}))}>{t('All',lang)}</Button><Button variant="ghost" aria-pressed={state.visible.length===1&&state.visible[0]==='skeletal'} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['skeletal']}))}>{t('Skeleton',lang)}</Button><Button variant="ghost" aria-pressed={state.visible.length===6&&['cardiac','respiratory','digestive','urinary','endocrine','reproductive'].every(id=>state.visible.includes(id as SystemId))} onClick={()=>setState(s=>({...s,selected:[],isolate:false,visible:['cardiac','respiratory','digestive','urinary','endocrine','reproductive']}))}>{t('Organs',lang)}</Button></div>
   <div className="system-list">{activeSystems.map(s=><div className={`system-row ${state.visible.includes(s.id)?'enabled':''}`} key={s.id}><Button variant="ghost" className="system-name" title={tf('Show only {name}',{name:systemLabel(s,lang)},lang)} onClick={()=>setState(v=>({...v,visible:[s.id],isolate:false,selected:[]}))}><span className="system-dot" style={{background:s.color}}/>{systemLabel(s,lang)}<span className="system-count">{counts[s.id]}</span></Button><Switch checked={state.visible.includes(s.id)} onCheckedChange={()=>toggle(s.id)} aria-label={tf('Show {name}',{name:systemLabel(s,lang)},lang)}/></div>)}</div>
   <div className="panel-foot"><span>{tf('{n} pieces visible',{n:visibleCount.toLocaleString()},lang)}</span><Button variant="ghost" onClick={()=>setState(s=>({...s,visible:[],selected:[],isolate:false}))}>{t('Hide all',lang)}</Button></div>
  </section>
  {panel==='search'&&<section className="search-panel glass" aria-label={t('Find anatomy',lang)}><div className="panel-heading"><span>{t('Find a structure',lang)}</span><Button variant="ghost" className="icon-button" onClick={()=>setPanel(null)} aria-label={t('Close search',lang)}><X size={18}/></Button></div><Combobox<Concept> items={results} value={null} onValueChange={value=>{if(value)choose(value);}} inputValue={query} onInputValueChange={setQuery} itemToStringLabel={c=>label(c.name,lang,c.id)} filter={null} open onOpenChange={open=>{if(!open)setPanel(null);}}><ComboboxInput autoFocus placeholder={t('Heart, femur, cranial nerve…',lang)} aria-label={t('Search named anatomical structures',lang)} showTrigger={false}/><ComboboxContent className="anatomy-search-results"><ComboboxEmpty>{t('No structures match your search.',lang)}</ComboboxEmpty><ComboboxList>{(c:Concept)=><ComboboxItem key={c.id} value={c}><span className="search-result-name">{label(c.name,lang,c.id)}</span><span className="small-number">{c.elements.length===1?t('1 piece',lang):tf('{n} pieces',{n:c.elements.length},lang)}</span></ComboboxItem>}</ComboboxList></ComboboxContent></Combobox><p className="search-note">{query?t('Showing up to 80 matches. Refine your search to find smaller structures.',lang):t('Start with a major organ, or search every named structure.',lang)}</p></section>}
  <nav className="view-controls glass" aria-label={t('Camera controls',lang)}>{(['three-quarter','front','side','back'] as View[]).map((v,i)=><Button variant="ghost" key={v} className={state.view===v?'active':''} aria-pressed={state.view===v} disabled={state.explode>.8&&v!=='front'} onClick={()=>setState(s=>({...s,view:v,reset:s.reset+1,rotate:false}))} title={t(VIEW_TITLES[v],lang)} aria-label={t(VIEW_TITLES[v],lang)}><span>{['¾','F','S','B'][i]}</span></Button>)}<i/><Button variant="ghost" disabled={state.explode>=.4} aria-label={state.rotate?t('Pause rotation',lang):t('Rotate body',lang)} title={t('Auto rotate',lang)} className={state.rotate?'active':''} onClick={()=>setState(s=>({...s,rotate:!s.rotate}))}>{state.rotate?<Pause size={17}/>:<RotateCw size={18}/>}</Button><Button variant="ghost" aria-label={t('Reset view and layers',lang)} title={t('Reset',lang)} onClick={reset}><RotateCcw size={17}/></Button></nav>
  <div className="scene-caption"><span className="caption-line"/><span>{state.isolate?(chosen?label(chosen.name,lang,chosen.id):t('SELECTED STRUCTURE',lang)):state.explode>.95?t('ANATOMICAL INVENTORY',lang):state.explode>.05?t('SEPARATED STRUCTURES',lang):t('ADULT HUMAN · MALE',lang)}</span><span className="caption-line"/></div>
  <div className="bottom-dock glass"><Button variant="ghost" className="mobile-only dock-layers" onClick={()=>openPanel('layers')} aria-label={t('Open system layers',lang)}><Layers3 size={20}/><span>{t('Systems',lang)}</span></Button><div className="explode-control"><div className="explode-label"><label id="explode-label">{t('Explode anatomy',lang)}</label><output>{Math.round(state.explode*100)}<span>%</span></output></div><Slider aria-labelledby="explode-label" min={0} max={100} step={1} value={[state.explode*100]} onValueChange={v=>setState(s=>({...s,explode:(Array.isArray(v)?v[0]:v)/100,view:(Array.isArray(v)?v[0]:v)>80?'front':s.view,rotate:false}))}/><div className="slider-endpoints"><span>{t('Assembled',lang)}</span><span>{t('Every piece',lang)}</span></div></div><Button variant="ghost" className="dock-reset" onClick={reset} aria-label={t('Assemble and reset',lang)}><RotateCcw size={18}/><span>{t('Reset',lang)}</span></Button></div>
  <footer className="studio-footer"><span>{state.explode>.8?t('Drag to pan',lang):t('Drag to orbit',lang)} <b>·</b> {t('Pinch to zoom',lang)} <b>·</b> {t('Tap to inspect',lang)}</span><Button variant="ghost" onClick={()=>{setDetails(false);setPanel(null);setAbout(true);}}>{t('Source & credits',lang)} <ArrowUpRight size={12}/></Button></footer>
  {progress<100&&!error&&<div className="loading glass" role="status"><Activity size={18}/><div><strong>{t('Preparing the anatomy',lang)}</strong><span>{progress}% · {tf('Loading {n} pieces',{n:atlas?.parts.length.toLocaleString()??'2,234'},lang)}</span><div className="loading-track"><i style={{width:`${progress}%`}}/></div></div></div>}
  {error&&<div className="loading glass error" role="alert"><p>{error}</p><Button variant="ghost" onClick={()=>location.reload()}>{t('Reload viewer',lang)}</Button></div>}
  <Sheet open={details&&selectedParts.length>0} modal={false} disablePointerDismissal onOpenChange={setDetails}><SheetContent initialFocus={detailTitle} className={`detail-sheet glass ${state.isolate?'is-isolated':''}`} showCloseButton={true}><div className="detail-header"><div className="detail-accent" style={{background:system?.color}}/><div className="eyebrow">{system?systemLabel(system,lang):t('ANATOMY',lang)}</div><SheetTitle ref={detailTitle} tabIndex={-1} className="structure-title">{chosen?label(chosen.name,lang,chosen.id):''}</SheetTitle></div><div className="detail-scroll" key={`${chosen?.id}-${state.isolate}-${lang}`}><SheetDescription className="structure-description">{chosen&&selected?explanation(chosen.name,selected.system,lang):''}</SheetDescription>{chosen&&!hasNamedExplanation(chosen.name)&&<span className="context-note">{t('System overview · structure identified from source anatomy',lang)}</span>}<div className="structure-meta"><span>{t('Atlas reference',lang)}<strong>{chosen?.id}</strong></span><span>{t('Selected pieces',lang)}<strong>{state.selected.length.toLocaleString()}</strong></span></div>{selectedParts.length>1&&<div className="member-list"><h3>{t('Included structures',lang)}</h3>{selectedParts.slice(0,50).map(p=><Button variant="ghost" key={p.id} onClick={()=>choosePart(p.id)}><span>{label(p.name,lang,p.conceptId)}</span><ChevronRight size={14}/></Button>)}{selectedParts.length>50&&<p>{tf('And {n} more modeled pieces.',{n:selectedParts.length-50},lang)}</p>}</div>}<a className="source-link" href="https://lifesciencedb.jp/bp3d/" target="_blank" rel="noreferrer">{t('View anatomical source',lang)} <ArrowUpRight size={14}/></a></div><div className="detail-actions"><Button className={`primary-action ${state.isolate?'active':''}`} onClick={()=>setState(s=>({...s,isolate:!s.isolate,explode:0}))}><Focus size={18}/>{state.isolate?t('Show surrounding anatomy',lang):t('Isolate structure',lang)}<ChevronRight size={16}/></Button><Button variant="ghost" className="secondary-action" onClick={()=>{setState(s=>({...s,selected:[],isolate:false}));setDetails(false);}}>{t('Clear selection',lang)}</Button></div></SheetContent></Sheet>
  <Sheet open={about} onOpenChange={setAbout}><SheetContent className="about-sheet glass"><div className="eyebrow">{t('SOURCE & SCOPE',lang)}</div><SheetTitle className="structure-title">{t('A body, revealed.',lang)}</SheetTitle><SheetDescription>{t('Explore the adult male reference anatomy from BodyParts3D.',lang)}</SheetDescription><div className="about-copy"><p><strong>{t('Male · BodyParts3D',lang)}</strong><br/>{t('2,234 individual meshes and 3,432 named concepts from an adult male reference anatomy.',lang)}</p><p>{t('This reference does not contain every human structure or variation. Named concepts can contain multiple pieces; each source mesh is rendered once.',lang)}</p><p>{t('Colors and system groupings are designed for exploration. The geometry is simplified for the web, and short explanations provide general educational context. This is an anatomical reference, not a diagnostic or surgical tool.',lang)}</p><h3>{t('Source',lang)}</h3><p>{t('BodyParts3D, © The Database Center for Life Science licensed under CC Attribution 4.0 International.',lang)}</p><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/lic.html" target="_blank" rel="noreferrer">{t('Dataset license',lang)} <ArrowUpRight size={14}/></a><a href="https://dbarchive.biosciencedbc.jp/en/bodyparts3d/download.html" target="_blank" rel="noreferrer">{t('Original geometry & metadata',lang)} <ArrowUpRight size={14}/></a><a href="https://academic.oup.com/nar/article/37/suppl_1/D782/1000752" target="_blank" rel="noreferrer">{t('Read the source publication',lang)} <ArrowUpRight size={14}/></a></div></SheetContent></Sheet>
 </main>;
}
