/** Build app/structure-zh.ts from fma_zh_compact.json (FMA id -> Chinese name).
 * Normalizes Traditional Chinese to Simplified and reports coverage against the atlas.
 * Re-run whenever the source dictionary changes: `node scripts/integrate-fma-zh.mjs`.
 */
import {readFileSync,writeFileSync} from 'node:fs';
import OpenCC from 'opencc-js';

const source=JSON.parse(readFileSync(new URL('../fma_zh_compact.json',import.meta.url),'utf8'));
const atlas=JSON.parse(readFileSync(new URL('../public/models/atlas.json',import.meta.url),'utf8'));
const toSimplified=OpenCC.Converter({from:'t',to:'cn'});

const dict={};
let trimmed=0,converted=0;
for(const [id,name] of Object.entries(source)){
  const clean=name.trim();
  if(!clean){console.warn(`skip empty translation: ${id}`);continue;}
  if(clean!==name.trim()&&clean!==name)trimmed++;
  const simplified=toSimplified(clean);
  if(simplified!==clean)converted++;
  if(!/[\u4e00-\u9fff]/.test(simplified))console.warn(`no CJK characters, keeping anyway: ${id} -> ${simplified}`);
  dict[id.toUpperCase()]=simplified;
}

/** Corrections for entries sourced from the Japanese BodyParts3D interface
 * (kana or Japanese-style kanji terms) and for mojibake. Keys are FMA ids. */
const FIXES={
 FMA7339:'右肺后段',FMA7359:'右肺前段',FMA7360:'右肺内侧段',FMA7362:'右肺后底段',FMA7363:'右肺外侧底段',FMA7364:'右肺前底段',FMA7365:'右肺内侧底段',FMA7366:'右肺上段',
 FMA7372:'左肺尖后段',FMA7373:'左肺前段',FMA7374:'左肺上舌段',FMA7375:'左肺下舌段',FMA7376:'左肺上段',FMA7377:'左肺内侧底段',FMA7378:'左肺前底段',FMA7379:'左肺外侧底段',FMA7380:'左肺后底段',
 FMA7383:'肺中叶',FMA8631:'右肺外侧底段动脉',FMA8671:'右肺底总静脉',FMA8674:'右肺下底静脉',FMA8676:'左肺底总静脉',FMA8714:'肾上段动脉',
 FMA9827:'上纵隔',FMA9828:'下纵隔',FMA9838:'前纵隔',FMA9839:'中纵隔',FMA9840:'后纵隔',FMA10665:'颈横动脉浅支',FMA13278:'肝右前段动脉',
 FMA13362:'肝右叶',FMA13363:'肝左叶',FMA14778:'肝右动脉',FMA14971:'大肠肌层',FMA15041:'结肠带',FMA15419:'门静脉右前支',FMA15422:'门静脉右后支',
 FMA20805:'旋股外侧动脉降支',FMA23065:'胸肩峰动脉肩峰支',FMA23067:'胸肩峰动脉三角肌支',FMA32558:'肌肉系统',
 FMA34677:'三角肌锁骨部',FMA34678:'三角肌肩峰部',FMA34679:'三角肌肩胛部',FMA34687:'胸大肌锁骨部',FMA34696:'胸大肌胸肋部',FMA34699:'胸大肌腹部',
 FMA37682:'肱二头肌短头',FMA37683:'肱二头肌长头',FMA37692:'肱三头肌长头',FMA37694:'肱三头肌外侧头',
 FMA38558:'旋前圆肌肱头',FMA38559:'旋前圆肌尺头',FMA38615:'尺侧腕屈肌肱头',FMA38616:'尺侧腕屈肌尺头',FMA43933:'足底内侧动脉浅支',
 FMA45887:'股二头肌长头',FMA45890:'股二头肌短头',FMA45956:'腓肠肌内侧头',FMA45959:'腓肠肌外侧头',
 FMA45969:'拇短屈肌内侧头',FMA45970:'拇短屈肌外侧头',FMA46014:'拇收肌斜头',FMA46015:'拇收肌横头',FMA46104:'拇短屈肌浅头',FMA46119:'拇收肌斜头',FMA46120:'拇收肌横头',
 FMA46609:'环甲肌直部',FMA46610:'环甲肌斜部',FMA50333:'胼胝缘动脉中间内侧支',FMA50427:'后交通动脉下丘脑支',
 FMA50577:'小脑上动脉外侧支',FMA50580:'小脑上动脉内侧支',FMA52572:'动眼神经上支',FMA52573:'动眼神经下支',FMA54393:'面部分区',
 FMA59837:'鼻中隔骨部',FMA59838:'鼻中隔软骨部',FMA62493:'海马',FMA68193:'内侧段动脉',FMA68194:'外侧段动脉',FMA68196:'中叶动脉',
 FMA70444:'肝右后段动脉',FMA70502:'肾下段动脉',FMA70503:'肾后段动脉',FMA71193:'胸腺叶',FMA71318:'手蚓状肌',FMA71319:'手骨间背侧肌',FMA86917:'腹肌群',
 FMA8627:'右上段动脉',FMA9578:'骨盆',FMA13324:'头静脉',FMA22908:'贵要静脉',FMA49187:'枕部',FMA72064:'胸椎(T1-T12)',
};
for(const [id,name] of Object.entries(FIXES)){if(dict[id]!==name)converted++;dict[id]=name;}

// Reject any residual Japanese kana or garbled characters after corrections.
const kana=Object.entries(dict).filter(([,v])=>/[\u3040-\u30ff\uff66-\uff9f]/.test(v));
if(kana.length)console.warn(`entries still contain kana/halfwidth kana: ${kana.map(([k])=>k).join(', ')}`);
const bracketed=Object.entries(dict).filter(([,v])=>/[|［］]/.test(v));
if(bracketed.length)console.warn(`entries still contain '|' or fullwidth brackets: ${bracketed.slice(0,10).map(([k,v])=>`${k}=${v}`).join(', ')}`);

// Coverage report against the live atlas.
const conceptIds=new Set(atlas.concepts.map(c=>c.id.toUpperCase()));
const covered=[...conceptIds].filter(id=>dict[id]).length;
const partCovered=atlas.parts.filter(p=>dict[p.conceptId.toUpperCase()]).length;
const uncovered=atlas.concepts.filter(c=>!dict[c.id.toUpperCase()]);
console.log(`dictionary: ${Object.keys(dict).length} entries (${converted} traditional converted, ${trimmed} whitespace cleaned)`);
console.log(`concepts covered: ${covered}/${conceptIds.size} (${Math.round(covered*100/conceptIds.size)}%)`);
console.log(`renderable parts covered: ${partCovered}/${atlas.parts.length} (${Math.round(partCovered*100/atlas.parts.length)}%)`);
console.log(`uncovered concepts sample: ${uncovered.slice(0,8).map(c=>c.name).join(' | ')}`);

const banner=`/** Chinese labels for atlas concepts, keyed by FMA id.
 * Generated by scripts/integrate-fma-zh.mjs from fma_zh_compact.json — do not edit by hand.
 */\nexport const ZH_BY_ID:Record<string,string> = `;
writeFileSync(new URL('../app/structure-zh.ts',import.meta.url),banner+JSON.stringify(dict,null,0).replace(/","/g,'",\n"')+';\n');
console.log('wrote app/structure-zh.ts');
